# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: homepage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import base_pb2 as base__pb2
import house_pb2 as house__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='homepage.proto',
  package='Proto',
  syntax='proto3',
  serialized_pb=b'\n\x0ehomepage.proto\x12\x05Proto\x1a\x0cheader.proto\x1a\nbase.proto\x1a\x0bhouse.proto\"\x8b\x01\n\x0c\x41\x63tivityInfo\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tsub_title\x18\x03 \x01(\t\x12\x13\n\x0bsearch_info\x18\x04 \x01(\t\x12\x1c\n\x06images\x18\x05 \x03(\x0b\x32\x0c.Proto.Image\x12\x13\n\x0b\x61\x63tivity_id\x18\x06 \x01(\r\x12\x11\n\tshow_flag\x18\x07 \x01(\r\"l\n\nInviteInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x13\n\x0binner_title\x18\x03 \x01(\t\x12\x15\n\rinner_content\x18\x04 \x01(\t\x12\x12\n\nthumbImage\x18\x05 \x01(\t\"\x8d\x01\n\x0f\x41\x63tivityNewInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tsub_title\x18\x02 \x01(\t\x12\x1c\n\x06images\x18\x03 \x03(\x0b\x32\x0c.Proto.Image\x12\x13\n\x0b\x61\x63tivity_id\x18\x04 \x01(\r\x12\x12\n\npre_render\x18\x05 \x01(\r\x12\x11\n\tshow_flag\x18\x07 \x01(\r\"\xc8\x01\n\x0b\x43ontentInfo\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.Proto.ContentType\x12%\n\x08\x61\x63tivity\x18\x02 \x01(\x0b\x32\x13.Proto.ActivityInfo\x12\x1f\n\x05house\x18\x03 \x01(\x0b\x32\x10.Proto.HouseInfo\x12!\n\x06invite\x18\x04 \x01(\x0b\x32\x11.Proto.InviteInfo\x12,\n\x0c\x61\x63tivity_new\x18\x05 \x01(\x0b\x32\x16.Proto.ActivityNewInfo\"\x1a\n\x0bHomePageReq\x12\x0b\n\x03uin\x18\x01 \x01(\r\"j\n\x0bHomePageRsp\x12\x1e\n\x06header\x18\xf4\x03 \x01(\x0b\x32\r.Proto.Header\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\x12!\n\x05items\x18\x03 \x03(\x0b\x32\x12.Proto.ContentInfo*\x87\x01\n\x0b\x43ontentType\x12\x0e\n\nSTART_TYPE\x10\x00\x12\x11\n\rACTIVITY_TYPE\x10\x01\x12\x0f\n\x0bSEARCH_TYPE\x10\x02\x12\x0e\n\nHOUSE_TYPE\x10\x03\x12\x0f\n\x0bINVITE_TYPE\x10\x05\x12\x15\n\x11\x41\x43TIVITY_NEW_TYPE\x10\x06\x12\x0c\n\x08\x45ND_TYPE\x10\x07\x32\x46\n\x0bRpcHomePage\x12\x37\n\x0bGetHomePage\x12\x12.Proto.HomePageReq\x1a\x12.Proto.HomePageRsp\"\x00\x62\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,base__pb2.DESCRIPTOR,house__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CONTENTTYPE = _descriptor.EnumDescriptor(
  name='ContentType',
  full_name='Proto.ContentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START_TYPE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEARCH_TYPE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOUSE_TYPE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVITE_TYPE', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITY_NEW_TYPE', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END_TYPE', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=800,
  serialized_end=935,
)
_sym_db.RegisterEnumDescriptor(_CONTENTTYPE)

ContentType = enum_type_wrapper.EnumTypeWrapper(_CONTENTTYPE)
START_TYPE = 0
ACTIVITY_TYPE = 1
SEARCH_TYPE = 2
HOUSE_TYPE = 3
INVITE_TYPE = 5
ACTIVITY_NEW_TYPE = 6
END_TYPE = 7



_ACTIVITYINFO = _descriptor.Descriptor(
  name='ActivityInfo',
  full_name='Proto.ActivityInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='Proto.ActivityInfo.title', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_title', full_name='Proto.ActivityInfo.sub_title', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_info', full_name='Proto.ActivityInfo.search_info', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='images', full_name='Proto.ActivityInfo.images', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity_id', full_name='Proto.ActivityInfo.activity_id', index=4,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='show_flag', full_name='Proto.ActivityInfo.show_flag', index=5,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=204,
)


_INVITEINFO = _descriptor.Descriptor(
  name='InviteInfo',
  full_name='Proto.InviteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='Proto.InviteInfo.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Proto.InviteInfo.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inner_title', full_name='Proto.InviteInfo.inner_title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inner_content', full_name='Proto.InviteInfo.inner_content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thumbImage', full_name='Proto.InviteInfo.thumbImage', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=314,
)


_ACTIVITYNEWINFO = _descriptor.Descriptor(
  name='ActivityNewInfo',
  full_name='Proto.ActivityNewInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='Proto.ActivityNewInfo.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_title', full_name='Proto.ActivityNewInfo.sub_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='images', full_name='Proto.ActivityNewInfo.images', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity_id', full_name='Proto.ActivityNewInfo.activity_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre_render', full_name='Proto.ActivityNewInfo.pre_render', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='show_flag', full_name='Proto.ActivityNewInfo.show_flag', index=5,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=458,
)


_CONTENTINFO = _descriptor.Descriptor(
  name='ContentInfo',
  full_name='Proto.ContentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Proto.ContentInfo.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity', full_name='Proto.ContentInfo.activity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='house', full_name='Proto.ContentInfo.house', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invite', full_name='Proto.ContentInfo.invite', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity_new', full_name='Proto.ContentInfo.activity_new', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=661,
)


_HOMEPAGEREQ = _descriptor.Descriptor(
  name='HomePageReq',
  full_name='Proto.HomePageReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='Proto.HomePageReq.uin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=689,
)


_HOMEPAGERSP = _descriptor.Descriptor(
  name='HomePageRsp',
  full_name='Proto.HomePageRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Proto.HomePageRsp.header', index=0,
      number=500, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='Proto.HomePageRsp.ret', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='Proto.HomePageRsp.err', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='Proto.HomePageRsp.items', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=797,
)

_ACTIVITYINFO.fields_by_name['images'].message_type = base__pb2._IMAGE
_ACTIVITYNEWINFO.fields_by_name['images'].message_type = base__pb2._IMAGE
_CONTENTINFO.fields_by_name['type'].enum_type = _CONTENTTYPE
_CONTENTINFO.fields_by_name['activity'].message_type = _ACTIVITYINFO
_CONTENTINFO.fields_by_name['house'].message_type = house__pb2._HOUSEINFO
_CONTENTINFO.fields_by_name['invite'].message_type = _INVITEINFO
_CONTENTINFO.fields_by_name['activity_new'].message_type = _ACTIVITYNEWINFO
_HOMEPAGERSP.fields_by_name['header'].message_type = header__pb2._HEADER
_HOMEPAGERSP.fields_by_name['items'].message_type = _CONTENTINFO
DESCRIPTOR.message_types_by_name['ActivityInfo'] = _ACTIVITYINFO
DESCRIPTOR.message_types_by_name['InviteInfo'] = _INVITEINFO
DESCRIPTOR.message_types_by_name['ActivityNewInfo'] = _ACTIVITYNEWINFO
DESCRIPTOR.message_types_by_name['ContentInfo'] = _CONTENTINFO
DESCRIPTOR.message_types_by_name['HomePageReq'] = _HOMEPAGEREQ
DESCRIPTOR.message_types_by_name['HomePageRsp'] = _HOMEPAGERSP
DESCRIPTOR.enum_types_by_name['ContentType'] = _CONTENTTYPE

ActivityInfo = _reflection.GeneratedProtocolMessageType('ActivityInfo', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVITYINFO,
  __module__ = 'homepage_pb2'
  # @@protoc_insertion_point(class_scope:Proto.ActivityInfo)
  ))
_sym_db.RegisterMessage(ActivityInfo)

InviteInfo = _reflection.GeneratedProtocolMessageType('InviteInfo', (_message.Message,), dict(
  DESCRIPTOR = _INVITEINFO,
  __module__ = 'homepage_pb2'
  # @@protoc_insertion_point(class_scope:Proto.InviteInfo)
  ))
_sym_db.RegisterMessage(InviteInfo)

ActivityNewInfo = _reflection.GeneratedProtocolMessageType('ActivityNewInfo', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVITYNEWINFO,
  __module__ = 'homepage_pb2'
  # @@protoc_insertion_point(class_scope:Proto.ActivityNewInfo)
  ))
_sym_db.RegisterMessage(ActivityNewInfo)

ContentInfo = _reflection.GeneratedProtocolMessageType('ContentInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONTENTINFO,
  __module__ = 'homepage_pb2'
  # @@protoc_insertion_point(class_scope:Proto.ContentInfo)
  ))
_sym_db.RegisterMessage(ContentInfo)

HomePageReq = _reflection.GeneratedProtocolMessageType('HomePageReq', (_message.Message,), dict(
  DESCRIPTOR = _HOMEPAGEREQ,
  __module__ = 'homepage_pb2'
  # @@protoc_insertion_point(class_scope:Proto.HomePageReq)
  ))
_sym_db.RegisterMessage(HomePageReq)

HomePageRsp = _reflection.GeneratedProtocolMessageType('HomePageRsp', (_message.Message,), dict(
  DESCRIPTOR = _HOMEPAGERSP,
  __module__ = 'homepage_pb2'
  # @@protoc_insertion_point(class_scope:Proto.HomePageRsp)
  ))
_sym_db.RegisterMessage(HomePageRsp)


import abc
from grpc.beta import implementations as beta_implementations
from grpc.early_adopter import implementations as early_adopter_implementations
from grpc.framework.alpha import utilities as alpha_utilities
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
class EarlyAdopterRpcHomePageServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetHomePage(self, request, context):
    raise NotImplementedError()
class EarlyAdopterRpcHomePageServer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def start(self):
    raise NotImplementedError()
  @abc.abstractmethod
  def stop(self):
    raise NotImplementedError()
class EarlyAdopterRpcHomePageStub(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetHomePage(self, request):
    raise NotImplementedError()
  GetHomePage.async = None
def early_adopter_create_RpcHomePage_server(servicer, port, private_key=None, certificate_chain=None):
  import homepage_pb2
  import homepage_pb2
  method_service_descriptions = {
    "GetHomePage": alpha_utilities.unary_unary_service_description(
      servicer.GetHomePage,
      homepage_pb2.HomePageReq.FromString,
      homepage_pb2.HomePageRsp.SerializeToString,
    ),
  }
  return early_adopter_implementations.server("Proto.RpcHomePage", method_service_descriptions, port, private_key=private_key, certificate_chain=certificate_chain)
def early_adopter_create_RpcHomePage_stub(host, port, metadata_transformer=None, secure=False, root_certificates=None, private_key=None, certificate_chain=None, server_host_override=None):
  import homepage_pb2
  import homepage_pb2
  method_invocation_descriptions = {
    "GetHomePage": alpha_utilities.unary_unary_invocation_description(
      homepage_pb2.HomePageReq.SerializeToString,
      homepage_pb2.HomePageRsp.FromString,
    ),
  }
  return early_adopter_implementations.stub("Proto.RpcHomePage", method_invocation_descriptions, host, port, metadata_transformer=metadata_transformer, secure=secure, root_certificates=root_certificates, private_key=private_key, certificate_chain=certificate_chain, server_host_override=server_host_override)

class BetaRpcHomePageServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetHomePage(self, request, context):
    raise NotImplementedError()

class BetaRpcHomePageStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetHomePage(self, request, timeout):
    raise NotImplementedError()
  GetHomePage.future = None

def beta_create_RpcHomePage_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import homepage_pb2
  import homepage_pb2
  request_deserializers = {
    ('Proto.RpcHomePage', 'GetHomePage'): homepage_pb2.HomePageReq.FromString,
  }
  response_serializers = {
    ('Proto.RpcHomePage', 'GetHomePage'): homepage_pb2.HomePageRsp.SerializeToString,
  }
  method_implementations = {
    ('Proto.RpcHomePage', 'GetHomePage'): face_utilities.unary_unary_inline(servicer.GetHomePage),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_RpcHomePage_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import homepage_pb2
  import homepage_pb2
  request_serializers = {
    ('Proto.RpcHomePage', 'GetHomePage'): homepage_pb2.HomePageReq.SerializeToString,
  }
  response_deserializers = {
    ('Proto.RpcHomePage', 'GetHomePage'): homepage_pb2.HomePageRsp.FromString,
  }
  cardinalities = {
    'GetHomePage': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'Proto.RpcHomePage', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
