# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms_router.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sms_router.proto',
  package='Proto',
  syntax='proto3',
  serialized_pb=b'\n\x10sms_router.proto\x12\x05Proto\"\x1c\n\x0cGetRouterReq\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"8\n\x0cGetRouterRsp\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t2D\n\tSmsRouter\x12\x37\n\tGetRouter\x12\x13.Proto.GetRouterReq\x1a\x13.Proto.GetRouterRsp\"\x00\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETROUTERREQ = _descriptor.Descriptor(
  name='GetRouterReq',
  full_name='Proto.GetRouterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Proto.GetRouterReq.data', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)


_GETROUTERRSP = _descriptor.Descriptor(
  name='GetRouterRsp',
  full_name='Proto.GetRouterRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Proto.GetRouterRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='Proto.GetRouterRsp.err', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='Proto.GetRouterRsp.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['GetRouterReq'] = _GETROUTERREQ
DESCRIPTOR.message_types_by_name['GetRouterRsp'] = _GETROUTERRSP

GetRouterReq = _reflection.GeneratedProtocolMessageType('GetRouterReq', (_message.Message,), dict(
  DESCRIPTOR = _GETROUTERREQ,
  __module__ = 'sms_router_pb2'
  # @@protoc_insertion_point(class_scope:Proto.GetRouterReq)
  ))
_sym_db.RegisterMessage(GetRouterReq)

GetRouterRsp = _reflection.GeneratedProtocolMessageType('GetRouterRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETROUTERRSP,
  __module__ = 'sms_router_pb2'
  # @@protoc_insertion_point(class_scope:Proto.GetRouterRsp)
  ))
_sym_db.RegisterMessage(GetRouterRsp)


import abc
from grpc.beta import implementations as beta_implementations
from grpc.early_adopter import implementations as early_adopter_implementations
from grpc.framework.alpha import utilities as alpha_utilities
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
class EarlyAdopterSmsRouterServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetRouter(self, request, context):
    raise NotImplementedError()
class EarlyAdopterSmsRouterServer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def start(self):
    raise NotImplementedError()
  @abc.abstractmethod
  def stop(self):
    raise NotImplementedError()
class EarlyAdopterSmsRouterStub(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetRouter(self, request):
    raise NotImplementedError()
  GetRouter.async = None
def early_adopter_create_SmsRouter_server(servicer, port, private_key=None, certificate_chain=None):
  import sms_router_pb2
  import sms_router_pb2
  method_service_descriptions = {
    "GetRouter": alpha_utilities.unary_unary_service_description(
      servicer.GetRouter,
      sms_router_pb2.GetRouterReq.FromString,
      sms_router_pb2.GetRouterRsp.SerializeToString,
    ),
  }
  return early_adopter_implementations.server("Proto.SmsRouter", method_service_descriptions, port, private_key=private_key, certificate_chain=certificate_chain)
def early_adopter_create_SmsRouter_stub(host, port, metadata_transformer=None, secure=False, root_certificates=None, private_key=None, certificate_chain=None, server_host_override=None):
  import sms_router_pb2
  import sms_router_pb2
  method_invocation_descriptions = {
    "GetRouter": alpha_utilities.unary_unary_invocation_description(
      sms_router_pb2.GetRouterReq.SerializeToString,
      sms_router_pb2.GetRouterRsp.FromString,
    ),
  }
  return early_adopter_implementations.stub("Proto.SmsRouter", method_invocation_descriptions, host, port, metadata_transformer=metadata_transformer, secure=secure, root_certificates=root_certificates, private_key=private_key, certificate_chain=certificate_chain, server_host_override=server_host_override)

class BetaSmsRouterServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetRouter(self, request, context):
    raise NotImplementedError()

class BetaSmsRouterStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def GetRouter(self, request, timeout):
    raise NotImplementedError()
  GetRouter.future = None

def beta_create_SmsRouter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import sms_router_pb2
  import sms_router_pb2
  request_deserializers = {
    ('Proto.SmsRouter', 'GetRouter'): sms_router_pb2.GetRouterReq.FromString,
  }
  response_serializers = {
    ('Proto.SmsRouter', 'GetRouter'): sms_router_pb2.GetRouterRsp.SerializeToString,
  }
  method_implementations = {
    ('Proto.SmsRouter', 'GetRouter'): face_utilities.unary_unary_inline(servicer.GetRouter),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_SmsRouter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import sms_router_pb2
  import sms_router_pb2
  request_serializers = {
    ('Proto.SmsRouter', 'GetRouter'): sms_router_pb2.GetRouterReq.SerializeToString,
  }
  response_deserializers = {
    ('Proto.SmsRouter', 'GetRouter'): sms_router_pb2.GetRouterRsp.FromString,
  }
  cardinalities = {
    'GetRouter': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'Proto.SmsRouter', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
